=== ajturner/GeoServicesREST-JSON/schemas/gsr/1.0/uniqueValueRenderer.json
{
   "$schema":"http://json-schema.org/draft-03/schema#",
   "id":"http://schemas.opengis.net/gsr/1.0/uniqueValueRenderer.json",

	"title":"simple renderer",
	"extends":{
		"$ref":"http://schemas.opengis.net/gsr/1.0/renderer.json"
	},
	"properties":{
		"type":{
			"title":"renderer type",
			"type":"string",
			"required":true,
			"enum":["uniqueValue"]
		},
		"field1":{
			"title":"name of first field",
			"type":["null","string"]
		},
		"field2":{
			"title":"name of second field",
			"type":["null","string"]
		},
		"field3":{
			"title":"name of third field",
			"type":["null","string"]
		},
		"fieldDelimiter":{
			"title":"field delimiter",
			"type":"string"
		},
		"defaultSymbol":{
			"$ref":"http://schemas.opengis.net/gsr/1.0/marker.json"
		},
		"defaultLabel":{
			"title":"default label",
			"type":"string"
		},
		"uniqueValueInfos":{
			"title":"unique values",
			"type":"array",
			"items":{
				"type":"object",
				"properties":{
					"value":{
						"type":"string"
					},
					"label":{
						"type":"string"
					},
					"description":{
						"type":"string"
					},
					"symbol":{
						"$ref":"http://schemas.opengis.net/gsr/1.0/marker.json"
					}
				}
			}
		}
	}
}

=== ajturner/GeoServicesREST-JSON/schemas/gsr/1.0/examples/uniqueValueRenderer.json
{
      "type" : "uniqueValue", 
      "field1" : "SubtypeCD", 
      "field2" : null, 
      "field3" : null, 
      "fieldDelimiter" : ", ", 
      "defaultSymbol" : 
      {
        "type" : "SLS", 
        "style" : "SLSSolid", 
        
        "color" : [130,130,130,255], 
        "width" : 1
      }, 
      "defaultLabel" : "Other values", 
      "uniqueValueInfos" : [
        {
          "value" : "1", 
          "label" : "Duct Bank", 
          "description" : "Duct Bank description", 
          "symbol" : 
          {
            "type" : "SLS", 
            "style" : "SLSDash", 
            
            "color" : [76,0,163,255], 
            "width" : 1
          }
        }, 
        {
          "value" : "2", 
          "label" : "Trench", 
          "description" : "Trench description", 
          "symbol" : 
          {
            "type" : "SLS", 
            "style" : "SLSDot", 
            
            "color" : [115,76,0,255], 
            "width" : 1
          }
        }
      ]
}
