=== ajturner/GeoServicesREST-JSON/schemas/gsr-gcs/1.0/root.json
{
   "$schema":"http://json-schema.org/draft-03/schema#",
   "id":"http://schemas.opengis.net/gsr-gcs/1.0/root.json",
   "title":"geocoding service root resource",
   "type":"object",
   "properties":{
      "serviceDescription":{
         "title":"service description",
         "description":"textual service description provided by the service author",
         "type":"string"
      },
      "addressFields":{
         "title":"address fields",
         "type":"array",
         "items":{
            "$ref":"http://schemas.opengis.net/gsr-gcs/1.0/addressField.json"
         }
      },
      "singleLineAddressField":{
        "title":"single line address field",
        "description":"if geocoding using a single line address is supported",
    	"$ref":"http://schemas.opengis.net/gsr-gcs/1.0/addressField.json"
      },
      "candidateFields":{
         "title":"candidate address fields",
         "type":"array",
         "items":{
            "$ref":"http://schemas.opengis.net/gsr-gcs/1.0/addressField.json"
         }
      },
      "intersectionCandidateFields":{
         "title":"candidate address fields",
         "type":"array",
         "items":{
            "$ref":"http://schemas.opengis.net/gsr-gcs/1.0/addressField.json"
         }
      },
      "spatialReference":{
    	"$ref":"http://schemas.opengis.net/gsr/1.0/spatialreference.json"
      },
      "locatorProperties":{
         "title":"locator properties",
         "$ref":"http://schemas.opengis.net/gsr/1.0/keyValuePairs.json"
      }
   }
}

=== ajturner/GeoServicesREST-JSON/schemas/gsr-gcs/1.0/examples/root.json
{
"serviceDescription" : "Test Geocode Service Description",
"addressFields": [
  {"name" : "Street", "alias" : "Street or Intersection", "required" : true, "type" : "FieldTypeString"},
  {"name" : "Zone", "alias" : "Zip Code", "required" : false, "type" : "FieldTypeString"}
], 
"singleLineAddressField" : {"name" : "Single Line Input","type" : "FieldTypeString","alias" : "Full Address","required" : false}
,
"candidateFields": [
  {"name" : "Score", "alias" : "", "type" : "FieldTypeSmallInteger"},
  {"name" : "StreetName", "alias" : "", "type" : "FieldTypeString"}
],
"intersectionCandidateFields": [
  {"name" : "Score", "alias" : "", "type" : "FieldTypeSmallInteger"},
  {"name" : "StreetName1", "alias" : "", "type" : "FieldTypeString"}
],
"spatialReference" : {"wkid" : 4326},
"locatorProperties": {
  "MinimumCandidateScore" : "10",
  "SideOffsetUnits" : "ReferenceDataUnits",
  "SpellingSensitivity" : "80",
  "MinimumMatchScore" : "60",
  "IntersectionConnectors" : "& | @"
}
}
